name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        git config --global user.email "${{github.actor}}@gmail.com"
        git config --global user.name "Zhian N. Kamvar (bot)"
        git config --list

